name: 'get-release-number'
description: 'Get next release number'
author: 'philipparndt'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'GitHub token'
runs:
  using: 'node16'
  main: 'dist/index.js'
