name: 'get-release-number'
description: 'Get next release number'
author: 'philipparndt'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'GitHub token'
  firstRelease:
    required: true
    description: 'Default first release number'
    default: '0.0.0'
  releaseType:
    required: true
    description: 'major, minor or patch'
outputs:
  version:
    description: 'next version'
runs:
  using: 'node12'
  main: 'dist/index.js'
